---
repos:
    - repo: local
      hooks:
          - id: prettier
            name: prettier
            entry: arches/app/media/node_modules/.bin/prettier arches/app/src --write
            language: script
